---
- hosts: localhost
  name: "Test the server setup from template"
#  become: true
  vars_files:
    - ../host.config

  tasks:
    - name: Create config files on the server.
      ansible.builtin.template:
        src: 'template.j2'
        dest: '/mnt/e/test/{{ item.name }}'
        mode: '0644'
      with_items: '{{ homelab_hosts }}'
      when: item.nginx | default(false)
#      loop:
#        - { name: hass, address: 'http://192.168.3.2:8123' }
#        - { name: nodered, address: 'http://192.168.3.4' }
