---
- name: Echo playbook
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../host.config

  tasks:
    - name: Set up nginx.
      ansible.builtin.debug:
        msg:
          - "This sets up nginx for {{ item.name }} at ip {{ item.ip }}"
      with_items: '{{ homelab_hosts }}'
      when: item.nginx | default(false)

    - name: Set up pihole.
      ansible.builtin.debug:
        msg:
          - "This sets up pihole for {{ item.name }} at ip {{ item.ip }}"
      with_items: '{{ homelab_hosts }}'
      when: item.pihole | default(false)

    - name: Test packages.
      ansible.builtin.debug:
        msg: "Installing package {{ item.packages }}"
      with_items: '{{ homelab_hosts }}'
      when: item.packages is defined
